<a href="https://colab.research.google.com/github/Merline-Biju/InternsoftCodeFiles/blob/main/numpyCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **THE NumPy PACKAGE**

In [1]:
import numpy as np

In [2]:
np_fake = np

In [3]:
np_fake is np

True

# Array Creation and Properties

In [ ]:
a = np.arange(10)
b = np.arange(20)

In [ ]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = range(20)
print(b)
print(list(b))

range(0, 20)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a = np.arange(10).reshape(3, 3) #error
a

ValueError: ignored

In [ ]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
print("Dimensions : " + str(a.ndim))
print("Shape : " + str(a.shape))
print("Size : " + str(a.size))
print("Datatype : " + str(a.dtype))
print("No of bytes of each element :" + str(a.itemsize))
print("Type : " + str(type(a)))

Dimensions : 2
Shape : (2, 5)
Size : 10
Datatype : int64
No of bytes of each element :8
Type : <class 'numpy.ndarray'>


In [ ]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [ ]:
b = np.array( [10.0 , 20.0, 30, 40.0] )

In [ ]:
print(b)
print(b.dtype)
print(type(b))

[10. 20. 30. 40.]
float64
<class 'numpy.ndarray'>


In [ ]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [ ]:
c = np.eye(5)
dtype = np.float64
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
c = np.eye(10)
dtype = np.int64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
d = np.linspace(-1, 2, 15, endpoint = True)
print(d)

[-1.         -0.78571429 -0.57142857 -0.35714286 -0.14285714  0.07142857
  0.28571429  0.5         0.71428571  0.92857143  1.14285714  1.35714286
  1.57142857  1.78571429  2.        ]


In [ ]:
d = np.linspace(0, 2, 15, endpoint = True)
print(d)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


In [ ]:
d = np.linspace(-1, 2, 2, endpoint = True)
print(d)

[-1.  2.]


In [ ]:
d = np.linspace(-1, 2, 1, endpoint=True)
print(d)

[-1.]


In [ ]:
d = np.linspace(-1, 2, 3, endpoint = True)
print(d)

[-1.   0.5  2. ]


In [ ]:
d = np.linspace(-1, 2, 5, endpoint = True)
print(d)

[-1.   -0.25  0.5   1.25  2.  ]


In [ ]:
d = np.linspace(-1, 2, 5, endpoint = False)
print(d)

[-1.  -0.4  0.2  0.8  1.4]


In [ ]:
e = np.logspace(-1, 2, 15, endpoint = True, base = 10)
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [ ]:
e = np.logspace(-1, 2, 5, endpoint = True, base = 10)
print(e)

[  0.1          0.56234133   3.16227766  17.7827941  100.        ]


In [ ]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [ ]:
f = np.fromfunction(lambda i, j: i == j , (3, 3), dtype = int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
f = np.fromfunction(lambda p, q: p < q , (3, 3), dtype = int)
print(f)

[[False  True  True]
 [False False  True]
 [False False False]]


In [ ]:
f = np.fromfunction(lambda p, q: p <= q , (3, 3), dtype = int)
print(f)

[[ True  True  True]
 [False  True  True]
 [False False  True]]


# Array Operations

In [ ]:
a = np.arange(16).reshape(4, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a + a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [ ]:
a * a #Mathematically wrong

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [ ]:
a = np.arange(10).reshape(2 , 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a * a #Mathematically wrong

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
print("a : \n" + str(a) + "\n")
b = a.transpose()
print("b : \n" + str(b))

a : 
[[0 1 2 3 4]
 [5 6 7 8 9]]

b : 
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
a * b #Mathematically and technically wrong

ValueError: ignored

In [ ]:
a @ b #Multipliction for matrix

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
a @ a #We should get an error 
      #because no of columns of first matrix != no of rows of second matrix

ValueError: ignored

In [ ]:
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
print(a.sum(axis = 1)) #column sum

[10 35]


In [ ]:
print(a.sum(axis = 0)) #row sum

[ 5  7  9 11 13]


In [ ]:
print(a.sum())

45


In [ ]:
print("Min : " + str(a.min()) + ", Max : " + str(a.max()))

Min : 0, Max : 9


# Universal Functions

In [ ]:
np.pi

3.141592653589793

In [ ]:
b = a * np.pi #Multiples of pi
b

array([[ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061],
       [15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388]])

In [ ]:
c = np.cos(b) #cos of multiples of pi
c

array([[ 1., -1.,  1., -1.,  1.],
       [-1.,  1., -1.,  1., -1.]])

In [ ]:
d = np.sin(b)
d

array([[ 0.00000000e+00,  1.22464680e-16, -2.44929360e-16,
         3.67394040e-16, -4.89858720e-16],
       [ 6.12323400e-16, -7.34788079e-16,  8.57252759e-16,
        -9.79717439e-16,  1.10218212e-15]])

In [ ]:
e = d / 10e-17
e

array([[ 0.        ,  1.2246468 , -2.4492936 ,  3.6739404 , -4.8985872 ],
       [ 6.123234  , -7.34788079,  8.57252759, -9.79717439, 11.02182119]])

In [ ]:
f = c + e
f

array([[ 1.        ,  0.2246468 , -1.4492936 ,  2.6739404 , -3.8985872 ],
       [ 5.123234  , -6.34788079,  7.57252759, -8.79717439, 10.02182119]])

# Array Slicing: Accessing Subarrays

In [ ]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
print(a[0], a[2], a[14])

0 2 14


In [ ]:
a[3:12]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# Multidimensional arrays

In [ ]:
a = a.reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
print(a[0, 0], a[1, 3], a[3, 3])

0 7 15


In [ ]:
a[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [ ]:
a[1:4, 0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
a[:, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
print(a[:, ::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [ ]:
print(a)
print("\n")
print(a[::-1, ::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [ ]:
a.sum(axis = 0)

array([24, 28, 32, 36])

In [ ]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
for i in a:
  print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [ ]:
a = a.reshape(2, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
for i in a.flat:
  print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [ ]:
help(a.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

# Copying Arrays

In [ ]:
a = np.arange(15)
print(a)
print("Memory of a : " + str(hex(id(a))))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Memory of a : 0x7f7dd5f05df0


In [ ]:
b = a
print(b)
print("Memory of b : " + str(hex(id(b))))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Memory of b : 0x7f7dd5f05df0


In [ ]:
b is a

True

In [ ]:
b.shape = (3, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
c = a[:] #Shallow copy
a.shape = (5, 3)

print(a)
print("\n")
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
print("Memory of a : " + str(hex(id(a))))
print("Memory of b : " + str(hex(id(b))))
print("Memory of c : " + str(hex(id(c))))

Memory of a : 0x7f7dd5f05df0
Memory of b : 0x7f7dd5f05df0
Memory of c : 0x7f7dd5f05120


In [ ]:
c[0, 0] = -1
print(c)
print("\n")
print(a)
print("\n")
print(b)

[[-1  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[-1  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
d = c[1::-1]
d

array([[ 5,  6,  7,  8,  9],
       [-1,  1,  2,  3,  4]])

In [ ]:
d[0,0] = -11
print(d)
print("\n")
print(c)
print("\n")
print(a)

[[-11   6   7   8   9]
 [ -1   1   2   3   4]]


[[ -1   1   2   3   4]
 [-11   6   7   8   9]
 [ 10  11  12  13  14]]


[[ -1   1   2]
 [  3   4 -11]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]]


In [ ]:
print(c is a)
print(c.base is a)
print(d.base is a)
print(d.base is c)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
True
False
False
True


In [ ]:
e = a.copy() #deep copy
e

array([[ -1,   1,   2],
       [  3,   4, -11],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14]])

In [ ]:
a[0, 0] = 50
print(a)
print("\n")
print(e)

[[ 50   1   2]
 [  3   4 -11]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]]


[[ -1   1   2]
 [  3   4 -11]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]]


In [ ]:
print("Memory of a : " + str(hex(id(a))))
print("Memory of e : " + str(hex(id(e))))
print(e is a)
print(e.base is a)
print(e.flags.owndata)

Memory of a : 0x7f7dd5f05df0
Memory of e : 0x7f7de1b87940
False
False
True


# Boolean Indexing

In [ ]:
a = np.arange(12).reshape(2, 6)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a[a > 3] = 0
a

array([[0, 1, 2, 3, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
a[a == 0] = -1
a

array([[-1,  1,  2,  3, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [ ]:
a == -1

array([[ True, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
a = np.arange(12).reshape(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a[np.logical_and(a > 3, a <=10 )] = 0
a

array([[ 0,  1,  2,  3,  0,  0],
       [ 0,  0,  0,  0,  0, 11]])

In [ ]:
a > 0

array([[False,  True,  True,  True, False, False],
       [False, False, False, False, False,  True]])

# Avoiding loops

In [ ]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint = False)
y = np.linspace(ymin, ymax, N, endpoint = False)

print(x.shape)
print(y.shape)
print(x)
print(y)

(32,)
(64,)
[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     0.765625 0.78125  0.796875 0.8125   0.828125 0.84375  0.859375
 0.875    0.890625 0.90625  0.921875 0.9375   0.953125 0.96875  0.984375]


In [ ]:
import time

In [ ]:
t0 = time.time()

g = np.zeros((M, N))
print(g)
print("\n")

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0 * np.pi * x[i] * y[j])

print(g)
print("\n")
        
t1 = time.time()

print("time elapsed: {} milliseconds".format((t1-t0) * 1000))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00306796  0.00613588 ...  0.18605515  0.18906866
   0.1920804 ]
 [ 0.          0.00613588  0.01227154 ...  0.365613    0.37131719
   0.37700741]
 ...
 [ 0.          0.08885355  0.17700422 ... -0.75520138 -0.69397146
  -0.62725182]
 [ 0.          0.09190896  0.18303989 ... -0.62005721 -0.54532499
  -0.4659765 ]
 [ 0.          0.0949635   0.18906866 ... -0.46325978 -0.37700741
  -0.28734746]]


time elapsed: 6.101846694946289 milliseconds


In [ ]:
x2, y2 = np.meshgrid(x, y, indexing = "ij")

print(x2, end = "\n\n")
print(y2, end = "\n\n")

print(x2[:, 0], end = "\n\n")
print(x2[0, :], end = "\n\n")

print(y2[:, 0], end = "\n\n")
print(y2[0, :])

[[0.      0.      0.      ... 0.      0.      0.     ]
 [0.03125 0.03125 0.03125 ... 0.03125 0.03125 0.03125]
 [0.0625  0.0625  0.0625  ... 0.0625  0.0625  0.0625 ]
 ...
 [0.90625 0.90625 0.90625 ... 0.90625 0.90625 0.90625]
 [0.9375  0.9375  0.9375  ... 0.9375  0.9375  0.9375 ]
 [0.96875 0.96875 0.96875 ... 0.96875 0.96875 0.96875]]

[[0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 ...
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]
 [0.       0.015625 0.03125  ... 0.953125 0.96875  0.984375]]

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [ ]:
t0 = time.time()
g2 = np.sin(2.0 * np.pi * x2 * y2)
t1 = time.time()
print("time elapsed: {} milliseconds".format((t1-t0) * 1000))

time elapsed: 0.32806396484375 milliseconds


# NumPy Standard Data Types

In [ ]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.zeros(10, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.zeros(10, dtype=np.complex64)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j], dtype=complex64)

# Array Concatenation and Splitting

In [ ]:
x = np.array([11, 22, 33, 44])
y = np.array([44, 33, 22, 11])
print(np.concatenate([x, y]))
print(np.concatenate([y, x]))

[11 22 33 44 44 33 22 11]
[44 33 22 11 11 22 33 44]


In [ ]:
z = [55 , 66, 77]
np.concatenate([x, y, z])

array([11, 22, 33, 44, 44, 33, 22, 11, 55, 66, 77])

In [ ]:
np.concatenate([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grid = np.array([[1,2,3],[4,5,6]])

In [ ]:
np.concatenate([ grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([ grid, grid[::-1]])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
x1, x2, x3, x4 = np.split(x, [3, 5, 8])
print(x1, x2, x3, x4)

[1 2 3] [4 5] [6 7 8] [ 9 10]


In [ ]:
grid = np.arange(25).reshape((5, 5))
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
left, right = np.hsplit(grid, [2])
print(left, end = "\n\n")
print(right)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


# Aggregates

In [4]:
x = np.arange(5, 15, 2)
print(x)
np.add.reduce(x)

[ 5  7  9 11 13]


45

In [5]:
np.multiply.reduce(x)

45045

In [6]:
np.subtract.reduce(x)

-35

In [7]:
print(x)
np.add.accumulate(x)

[ 5  7  9 11 13]


array([ 5, 12, 21, 32, 45])

In [8]:
print(x)
np.multiply.accumulate(x)

[ 5  7  9 11 13]


array([    5,    35,   315,  3465, 45045])

In [9]:
print(x)
np.subtract.accumulate(x)

[ 5  7  9 11 13]


array([  5,  -2, -11, -22, -35])